import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f6e6f3ff",
  },
  content: {
    flex: 1,
    justifyContent: "center",
    padding: 24,
  },
  logoContainer: {
    alignItems: "center",
    marginBottom: 6,
  },
  header: {
    marginBottom: 40,
  },
  title: {
    fontSize: 48,
    fontWeight: "800",
    color: "#390505ff",
    letterSpacing: 1,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 18,
    color: "#94A3B8",
    marginTop: 8,
  },
  form: {
    gap: 16,
  },
  input: {
    flex: 1,
    paddingVertical: 18,
    fontSize: 20,
  },
  button: {
    backgroundColor: "#3B82F6",
    padding: 18,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 8,
    shadowColor: "#3B82F6",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
    width: "80%",
    alignSelf: "center",
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "600",
  },
  footer: {
    flexDirection: "column",
    justifyContent: "center",
    marginTop: 24,
  },
  footerText: {
    color: "#94A3B8",
    fontSize: 20,
  },
  linkText: {
    color: "blue",
    fontSize: 24,
    fontWeight: "600",
  },
  inputIcon: {
    marginRight: 14,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 20,
    borderWidth: 1,
    shadowColor: "#0a0912ff",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 5,
    borderColor: "#eef1f4ff",
    paddingHorizontal: 16,
  },
  label: {
    color: "#000",
    fontSize: 20,
    fontWeight: "600",
  },
  buttonContainer: {
    width: "80%",
    alignSelf: "center",
    marginTop: 30,
  },
  gradientButton: {
    padding: 18,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  labelContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  separator: {
    width: "25%",
    height: 1,
    backgroundColor: "#313438ff",
    marginHorizontal: 10,
    marginTop: 15,
  },
  iconCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 5,
    borderColor: "#FFFFFF",
    shadowColor: "#C471ED",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 10,
  },
  socialContainer: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 40,
    marginTop: 24,
  },
  socialButton: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
    elevation: 10,
  },
  footer2: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 24,
  },
  footerText2: {
    color: "#000",
    fontSize: 24,
    fontWeight: "normal",
  },
  // ── SignUp-specific ──────────────────────────────────────────────
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 28,
    paddingVertical: 32,
  },
  signUpTitle: {
    fontSize: 36,
    fontWeight: "800",
    color: "#1a1a2e",
    textAlign: "center",
    marginBottom: 28,
    marginTop: 8,
  },
  signUpForm: {
    gap: 10,
  },
  signUpButtonContainer: {
    marginTop: 20,
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#7F5AF0",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 8,
  },
  signUpGradientButton: {
    paddingVertical: 18,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
  },
  signUpButtonText: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  separatorRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    gap: 8,
  },
  separatorLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#d0c8e0",
  },
  separatorText: {
    fontSize: 20,
    color: "#676767ff",
    fontWeight: "500",
  },
  footerRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 8,
  },
  signUpFooterText: {
    fontSize: 20,
    color: "#000000ff",
  },
  footerLink: {
    fontSize: 20,
    fontWeight: "700",
    color: "#7F5AF0",
  },
});

export default styles;
